### ISSUE TITLE
IllegalStateException regarding the response channel during a web request

### ISSUE THREAD

**Issue by AegeusCoin** [tdiesler/nessus#43]
The commit seen here - https://github.com/AegeusCoin/aegeus-ui/commit/8fe107f3b313b8b748d6c232986c8eca98a30d25 has introduced the following exceptions:

java.lang.IllegalStateException: UT000002: The response has already been started
at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1406)
at io.undertow.server.handlers.RedirectHandler.handleRequest(RedirectHandler.java:64)
at io.aegeus.ipfs.portal.ContentHandler.actAddURL(ContentHandler.java:298)
at io.aegeus.ipfs.portal.ContentHandler.pageContent(ContentHandler.java:116)
at io.aegeus.ipfs.portal.ContentHandler.handleRequest(ContentHandler.java:77)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)

as well as:

java.lang.IllegalStateException: UT000004: getResponseChannel() has already been called
at io.undertow.io.AsyncSenderImpl.send(AsyncSenderImpl.java:146)
at io.undertow.io.AsyncSenderImpl.send(AsyncSenderImpl.java:285)
at io.aegeus.ipfs.portal.ContentHandler.handleRequest(ContentHandler.java:90)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)

This is reproducible by taking the following steps:

1. Pull the latest 'devel' branch down from https://github.com/AegeusCoin/aegeus-ui
2. Build it
3. Access the web portal
4. Visit the file manager
5. Click "Add By URL"
6. Insert any URL here
7. docker logs aeg-webui

The code in question does successfully operate in terms of identifying content type as well as the size, and responds appropriately based on conditions defined.

**Comment by tdiesler** [comment]
This may have become out of date due to the undertow update. 
Please reopen if you're still seeing this with the latest.
